runners:
 example-runner:
  image: stag:5000/ubuntu-vitis-2020-1

jobs:   
 run-hw-vec:
  resource_spec: small  
  runner: example-runner
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/vec
  device: zcu104-device-vitis-reboot  
  input: 
   artifact: 
    - build-vec.tar.gz
  steps:
   - run:
      name: Setup
      command: apt-get install sshpass  
   - transfer:
      name: Transfer
      SOURCE: Hardware/package/sd_card/*
      DESTINATION: root@192.168.1.86:/mnt/sd-mmcblk0p1/
   - run:
      name: Reboot
      on-device: True
      command: |
       set_reboot sys
       reboot

   - run:
      name: Run device
      on-device: True
      pass: TEST PASSED
      fail: TEST FAILED
      command: |      
       cd /mnt
       cd sd-mmcblk0p1
       source ./init.sh
       export XILINX_XRT=/usr
       ./vector_add binary_container_1.xclbin

 
workflows:
 vec-hw-test:
  jobs:
   - run-hw-vec