runners:
 example-runner:
  image: stag:5000/ubuntu-vitis-2020-1

jobs:   
 build-hw-vec:
  resource_spec: 1.5xlarge  
  runner: example-runner
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/vec    
  input: 
   artifact: 
    - xilinx_zcu104_base_202010_1.zip
    - aarch64-xilinx-linux2020_1.zip
    - xilinx-zynqmp-common-v2020.1.tar.gz
    - Vitis_Libraries_2020_1.tar.gz
  output:
   artifact:
    - hw.sh
    - Hardware/build.sh
    - Hardware/sleep.sh
    - Hardware/ssh_retry.sh
    - Hardware/run.expect
    - Hardware/transfer.expect
    - Hardware/package    
  steps:
   - run:
      name: Run Hardware Build
      command: Hardware/build.sh

 run-hw-vec:
  resource_spec: small  
  runner: example-runner
  current_working_directory: /tools/Xilinx/Vitis/2020.1/workspace/vec
  device: zcu104-device-vitis  
  depends:
   - build-hw-vec
  input: 
   artifact: 
    - build-hw-vec
  steps:
   - run:
      name: Setup
      command: apt-get install sshpass  
   - transfer:
      name: Transfer
      SOURCE: Hardware/package/sd_card/*
      DESTINATION: root@192.168.1.86:/mnt/sd-mmcblk0p1/      
   - run:
      name: Run device
      on-device: True
      pass: TEST PASSED
      fail: TEST FAILED
      command: |      
       cd /mnt
       cd sd-mmcblk0p1
       source ./init.sh
       export XILINX_XRT=/usr
       ./vector_add binary_container_1.xclbin

 
workflows:
 vec-hw-build-test:
  jobs:
   - build-hw-vec
   - run-hw-vec
